### ISSUE TITLE
Stuck on monochrome

### ISSUE THREAD

**Issue by licaon-kter** [theblixguy/Monochrome#2]
Xperia, 5.1.1, battery low, display goes monochrome, device shuts down, charge device to 100%, open device, display still monochrome, stop app, reboot, device still monochrome, uninstall app, reboot, device still monochrome.

Ideas?

**Comment by theblixguy** [comment]
Use the Reset option in the app

**Comment by licaon-kter** [comment]
Ok, that fixes it, thanks.

Small complaint, do rename that option with something more in the lines of "reset display to colour", add this info to the app help, add that info on GitHub/XDA and add it to the Google Play store too.

I though that this option will somehow resets the app settings (like the Android "clear data"), not the app actions (toggle to colour).

/LE: made some PRs with these
